name: Deploy

on:
  push:
    branches:
    - master

jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@master
    - name: Checkout Node
      uses: actions/setup-node@master
      with:
        node-version: '10.x'
    - name: Npm install in Angular App
      run: npm install
    - name: Npm install in functions
      run: npm install
      working-directory: functions
    - name: Build Angular App
      run: npm run build:prod
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy -P prod --only hosting,functions
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
